name: 'Terraform cluster, parameterised'
description: 'Terraform cluster, parameterised'
inputs:
  BRANCH:
    required: true
  SERVICE:
    required: true
  TF_API_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.BRANCH }}


    # Terraform the GCR service 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
      shell: bash

    # Pass docker image name to terraform as input var 
    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -var="service-name=${{ inputs.SERVICE }}" -auto-approve -input=false
      shell: bash  
